language: node_js
node_js:
- '4.2'
sudo: false
notifications:
  email: true
cache:
  directories:
  - node_modules
  - src/bower_components
  - typings
script: npm run build
after_failure: cat /home/travis/build/hafizahmedattari/angular2-quickstart/npm-debug.log
branches:
  only:
  - master
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
